## control model integration
random_seed: 3142
steps_to_run: 100


## input / output files
output_directory: output

## visualisation
# visualisation: pdf
# visualisation: window
# visualisation: jupyterlab
visualisation: solara

## size of the model
grid_length: 10


land_use_rules:
  basic: True
  neighbour: True
  network: True

## fixed_parameters_of_the_mode
farmer_behaviour:

  business_as_usual:
    initial_distribution: 33

  industry_conscious:
    initial_distribution: 33

  climate_conscious:
    initial_distribution: 34

## number_of_farmer_networks
number_of_land_use_networks: 2

## the_period_over_which_farmers_re-evaluate_their_land_use
occurrence_max: 30

## land_uses
land_use:

  artificial:
    label: Artificial
    code: 1
    value: 50000 
    CO2eq: 0     
    initial_distribution: 3  
    color: 'red'

  water: 
    label: Water
    code: 2
    value: 0     
    CO2eq: 0     
    initial_distribution: 5  
    color: 'blue'

  crop_annual: 
    label: Crop annual
    code: 3
    value: 2000  
    CO2eq: 95    
    initial_distribution: 10  
    color: 'green'
  
  crop_perennial: 
    label: Crop perennial
    code: 4
    value: 15000 
    CO2eq: 90    
    initial_distribution: 10  
    color: 'orange'
  
  scrub: 
    label: Scrub
    code: 5
    value: 0     
    CO2eq: -100  
    initial_distribution: 18  
    color: 'black'

  intensive_pasture: 
    label: Intensive_pasture
    code: 6
    value: 4000  
    CO2eq: 480   
    initial_distribution: 23  
    color: 'magenta'

  extensive_pasture: 
    label: Extensive pasture
    code: 7
    value: 1400  
    CO2eq: 150   
    initial_distribution: 6  
    color: 'brown'

  native_forest: 
    label: Native_forest
    code: 8
    value: 0     
    CO2eq: -250  
    initial_distribution: 5  
    color: 'cyan'

  exotic_forest: 
    label: Exotic forest
    code: 9
    value: 1150  
    CO2eq: -700  
    initial_distribution: 20  
    color: 'grey'



