## input / output files
output_directory: output

## visualisation
visualisation: pdf
# visualisation: png
# visualisation: window
# visualisation: jupyterlab
# visualisation: solara

## control non-interactive model integration
random_seed: 3142
steps_to_run: 10

# ## model space, size, shape
# space:
  # type: grid
  # x: 10
  # y: 15

space:
  type: raster layer
  filename: test/gis_data/Mosquitos_10x10.grd

## decision making rules
land_use_rules:
  basic: True
  neighbour: True
  network: True

## fixed_parameters_of_the_mode
farmer_behaviour:

  business_as_usual:
    initial_distribution: 33

  industry_conscious:
    initial_distribution: 33

  climate_conscious:
    initial_distribution: 34

## number_of_farmer_networks
number_of_land_use_networks: 2

## the_period_over_which_farmers_re-evaluate_their_land_use
occurrence_max: 30

## land_uses
land_use:

  1:
    label: Artificial
    value: 50000 
    CO2eq: 0     
    initial_distribution: 3  
    color: 'red'

  2:
    label: Water
    value: 0     
    CO2eq: 0     
    initial_distribution: 5  
    color: 'blue'

  3:
    label: Crop annual
    value: 2000  
    CO2eq: 95    
    initial_distribution: 10  
    color: 'green'
  
  4:
    label: Crop perennial
    value: 15000 
    CO2eq: 90    
    initial_distribution: 10  
    color: 'orange'
  
  5:
    label: Scrub
    value: 0     
    CO2eq: -100  
    initial_distribution: 18  
    color: 'black'

  6:
    label: Intensive_pasture
    value: 4000  
    CO2eq: 480   
    initial_distribution: 23  
    color: 'magenta'

  7:
    label: Extensive pasture
    value: 1400  
    CO2eq: 150   
    initial_distribution: 6  
    color: 'brown'

  8:
    label: Native forest
    value: 0     
    CO2eq: -250  
    initial_distribution: 5  
    color: 'cyan'

  9:
    label: Exotic forest
    value: 1150  
    CO2eq: -700  
    initial_distribution: 20  
    color: 'grey'



