# -*- compile-command: "./build_conda_environment.bash" ; -*-
## a file defining a conda environment providing dependencies for this project 

channels:
  - conda-forge

dependencies:

  ## run the model and produce static figures
  - python
  - mesa
  - matplotlib
  - numpy
  - omegaconf

  ## for interactive matplotlib figure windows
  - qt
  - pyqt

  ## for jupyter lab interactive interaction
  - jupyterlab
  - ipywidgets
  - reacton
  - solara
  # - nodejs
  # - seaborn

  ## solara
  - solara

  ## post installation
  - pip
  - git
  # # - ca-certificates
